-- 删除所有表（如果存在）
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CheckInLog CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FavoriteWord CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE WrongWord CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ReviewSchedule CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE StudyLog CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE WordPhrase CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE WordTranslation CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Word CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE WordList CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "User" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 创建用户表
CREATE TABLE "User" (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('student', 'teacher', 'admin'))
);

-- 创建词表
CREATE TABLE WordList (
    list_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_name VARCHAR2(100) NOT NULL,
    description CLOB,
    creator_id NUMBER,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_public NUMBER(1) DEFAULT 1,
    difficulty VARCHAR2(20) DEFAULT 'CET-4',
    CONSTRAINT fk_wordlist_user FOREIGN KEY (creator_id) REFERENCES "User"(user_id)
);

-- 创建单词表
CREATE TABLE Word (
    word_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id NUMBER,
    word VARCHAR2(100) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_word_wordlist FOREIGN KEY (list_id) REFERENCES WordList(list_id) ON DELETE CASCADE
);

-- 创建单词翻译表
CREATE TABLE WordTranslation (
    translation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id NUMBER,
    translation CLOB NOT NULL,
    word_type VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_wordtranslation_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE
);

-- 创建单词短语表
CREATE TABLE WordPhrase (
    phrase_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id NUMBER,
    phrase CLOB NOT NULL,
    translation CLOB NOT NULL,
    CONSTRAINT fk_wordphrase_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE
);

-- 创建学习记录表
CREATE TABLE StudyLog (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    word_id NUMBER,
    study_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_studylog_user FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_studylog_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE,
    CONSTRAINT chk_studylog_status CHECK (status IN ('known', 'unknown', 'learning'))
);

-- 创建复习计划表
CREATE TABLE ReviewSchedule (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    word_id NUMBER,
    review_date TIMESTAMP NOT NULL,
    repeat_count NUMBER DEFAULT 0,
    memory_strength NUMBER(3,2) DEFAULT 0.5,
    CONSTRAINT fk_reviewschedule_user FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_reviewschedule_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE
);

-- 创建错词本表
CREATE TABLE WrongWord (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    word_id NUMBER,
    wrong_count NUMBER DEFAULT 1,
    last_wrong_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    error_type VARCHAR2(50) DEFAULT '含义理解',
    user_answer CLOB,
    CONSTRAINT fk_wrongword_user FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_wrongword_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE
);

-- 创建收藏词汇表
CREATE TABLE FavoriteWord (
    fav_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    word_id NUMBER,
    fav_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favoriteword_user FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_favoriteword_word FOREIGN KEY (word_id) REFERENCES Word(word_id) ON DELETE CASCADE
);

-- 创建打卡记录表
CREATE TABLE CheckInLog (
    checkin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    checkin_date DATE DEFAULT CURRENT_DATE,
    word_count NUMBER DEFAULT 0,
    study_duration NUMBER DEFAULT 0,
    accuracy_rate NUMBER(5,2) DEFAULT 0,
    CONSTRAINT fk_checkinlog_user FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX idx_word_list ON Word(list_id);
CREATE INDEX idx_word_translation ON WordTranslation(word_id);
CREATE INDEX idx_word_phrase ON WordPhrase(word_id);
CREATE INDEX idx_study_user ON StudyLog(user_id);
CREATE INDEX idx_study_word ON StudyLog(word_id);
CREATE INDEX idx_study_time ON StudyLog(study_time);
CREATE INDEX idx_review_user ON ReviewSchedule(user_id);
CREATE INDEX idx_review_date ON ReviewSchedule(review_date);
CREATE INDEX idx_wrong_user ON WrongWord(user_id);
CREATE INDEX idx_fav_user ON FavoriteWord(user_id);
CREATE INDEX idx_checkin_user ON CheckInLog(user_id);
CREATE INDEX idx_checkin_date ON CheckInLog(checkin_date);

-- 添加correct_answer列到WrongWord表
ALTER TABLE WrongWord ADD (correct_answer CLOB);